# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Oxi OS Keyboard Module Configuration
---
layoutList:
    - us
    - de
    - fr
    - tr
    - es
    - it
    - pt
    - ru
    - cn
    - jp
    - kr
variantList: []
modelList: []
