# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Oxi OS Locale Module Configuration
---
timezone:
    allowGeoIp: false
    zoneList:
        - Europe
        - America
        - Asia
        - Africa
        - Australia
        - Pacific
        - Atlantic
        - Indian
        - Arctic
        - Antarctica

locale:
    allowGeoIp: false
    localesList: []
