---
defaultFileSystemType: xfs
availableFileSystemTypes:
  - xfs

efiSystemPartition: /boot/efi
enableLuksAutomatedPartitioning: true
userSwapChoices:
  - none
initialPartitioningChoice: erase
drawNestedPartitions: true
alwaysShowPartitionLabels: true
