# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Oxi OS Partition Module Configuration
---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300MiB
    minimumSize: 32MiB
    label: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: true
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "xfs"
availableFileSystemTypes:
    - "xfs"

directoryFilesystemRestrictions:
    - directory: "/"
      allowedFilesystemTypes: ["xfs"]
    - mountpoint: "efi"
      allowedFilesystemTypes: ["fat32"]
      onlyWhenMountpoint: true

lvm:
    enable: true

enableLuksAutomatedPartitioning: true
