# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Oxi OS Users Module Configuration
---
defaultGroups:
    - audio
    - video
    - network
    - lpadmin
    - scanner
    - sambashare
    - plugdev
    - cdrom
    - floppy
    - dialout

autologinGroup: autologin
sudoersGroup: sudo
setRootPassword: false
allowWeakPasswords: false
