# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Oxi OS Welcome Module Configuration
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: "https://github.com/oxi-os/oxi-os"

requirements:
    requiredStorage: 8.0
    requiredRam: 2.0
    internetCheckUrl: "https://github.com/oxi-os/oxi-os"
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - ram

geoip:
    style: "none"
